### ISSUE TITLE
Add support for itertools Merge, MergeBy, KMerge, KMergeBy

### ISSUE THREAD

**Issue by CarlKCarlK** [rklaehn/sorted-iter#3]
Great library, I'm learning much just from using it.
I believe KMergeBy from itertools returns sorted items and could be marked as SortedByKey.
- Carl

**Comment by rklaehn** [comment]
I have thought about this as well. It would have to be a non default feature that adds a dependency to itertools and then defines the appropriate marker traits. Would that work for you?

I don't want to have a default dependency on itertools.

**Comment by CarlKCarlK** [comment]
That would be great!
This might not make sense for you to do this for every 3rd-party crate, but itertools seems special and popular.

  *   Carl

**Comment by rklaehn** [comment]
Not sure how you would support the MergeBy variants, since you really don't know what is inside that predicate...

But here is a draft PR for Merge/KMerge. https://github.com/rklaehn/sorted-iter/pull/6

**Comment by rklaehn** [comment]
Hm, I don't think supporting itertools merge will work. The output is sorted, but not strictly sorted.

https://docs.rs/itertools/latest/itertools/trait.Itertools.html#method.merge

```rust
use itertools::Itertools;

let a = (0..11).step(3);
let b = (0..11).step(5);
let it = a.merge(b);
itertools::assert_equal(it, vec![0, 0, 3, 5, 6, 9, 10]);
```

Note the double `0`.

**Comment by CarlKCarlK** [comment]
Good point!
