### ISSUE TITLE
Have Box<dyn SortedByItem> implement SortedByItem

### ISSUE THREAD

**Issue by CarlKCarlK** [rklaehn/sorted-iter#4]
I'm loving the library. Here is something that I think would help me:

impl SortedByItem for Box<dyn SortedByItem> {}

likewise for SortedbyKeys (and, I guess, Rc and Arc).

Thanks,
Carl
https://github.com/CarlKCarlK & https://medium.com/@carlmkadie

**Comment by rklaehn** [comment]
Yes, this sounds like it should definitely be done. Does not require any additional deps etc.

**Comment by CarlKCarlK** [comment]
Hold off on doing anything with this. I'm playing today with a perhaps better way to handle Box.

**Comment by rklaehn** [comment]
Too late... But it is not merged yet.

Curious what could be better. This seems pretty straightforward.

**Comment by rklaehn** [comment]
Is there anything wrong with the straightforward approach in #5 ? Otherwise I will merge it.

**Comment by CarlKCarlK** [comment]
Seems good!
